### ISSUE TITLE
 Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by msteen-google** [analyticsatbeslistpuntnl/beslist-event-gtm-template#1]
https://github.com/analyticsatbeslistpuntnl/beslist-event-gtm-template/blob/eab82db1a8cf8cf40ace455f8b2ce6c9d73286d8/template.tpl#L112

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by analyticsatbeslistpuntnl** [comment]
Thank you for your feedback.
We have updatet the script and commited the change: https://github.com/analyticsatbeslistpuntnl/beslist-event-gtm-template/commit/0171455fa4d9a4ff44d4f91de440879ff2eeddac
